name: build_and_test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      OPEN_SPIEL_ENABLE_JAX: ON
      OPEN_SPIEL_ENABLE_PYTORCH: ON
      OPEN_SPIEL_ENABLE_TENSORFLOW: ON
      OPEN_SPIEL_ENABLE_PYTHON_MISC: ON
      OS_PYTHON_VERSION: ${{ matrix.OS_PYTHON_VERSION }}
      TRAVIS_USE_NOX:  ${{ matrix.TRAVIS_USE_NOX }}
      DEFAULT_OPTIONAL_DEPENDENCY: ${{ matrix.DEFAULT_OPTIONAL_DEPENDENCY }}
      OPEN_SPIEL_BUILD_WITH_JULIA: ${{ matrix.OPEN_SPIEL_BUILD_WITH_JULIA }}
      BUILD_SHARED_LIB:  ${{ matrix.BUILD_SHARED_LIB }}
      OPEN_SPIEL_BUILD_WITH_ORTOOLS:  ${{ matrix.OPEN_SPIEL_BUILD_WITH_ORTOOLS }}
      OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL:  ${{ matrix.OPEN_SPIEL_BUILD_WITH_ORTOOLS_DOWNLOAD_URL }}

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        registry: docker.pkg.github.com
        password: ${{ github.token }}
        repository: ${{ github.repository }}/docker
        cache_froms: ${{ github.repository }}/docker:latest
        tag_with_ref: true